### ISSUE TITLE
Strange scrolling behavior

### ISSUE THREAD

**Issue by oliger** [hull-ships/hull-login#21] opened 2015-06-25 22:23 UTC
The dialog should not scroll. https://cloudup.com/c1A4inbDJ2y

**Comment by citelao** [comment] 2015-06-29 16:14
Self note: overlay/index.jsx, line 144; change `position: 'absolute'` to `position: 'fixed'`.

**Comment by citelao** [comment] 2015-07-10 14:54
Dupe of #18

**Closed by citelao** 2015-07-10 14:54 UTC
