### ISSUE TITLE
When installing the ship and embedding it as platform without going through configuration, a weird form object is shown

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-login#15] opened 2015-06-24 10:09 UTC
![screen shot 2015-06-24 at 12 08 32](https://cloud.githubusercontent.com/assets/9458/8327590/e1453444-1a69-11e5-9415-6f3d37d11a8c.png)

**Comment by citelao** [comment] 2015-06-24 13:47
Fixed in #14

**Comment by oliger** [comment] 2015-06-24 13:48
Duplicate of #12 and fixed in #14.

**Closed by oliger** 2015-06-24 13:48 UTC
Labels: bug
